### ISSUE TITLE
Extension not works in new version of MakeCode

### ISSUE THREAD

**Issue by EmmetBrickHacker** [philipphenkel/pxt-powerfunctions#4]
Hi Philipp!
First I want to thank you for this material. Unfortunately, I must say that with new version of MakeCode package is not functional again - https://makecode.microbit.org/v0 and https://makecode.microbit.org/v1 works well, but latest version dont make connection.

Is there some way how to fix it again? Thank you very much!

Just for information: Im using Grove - Infrared Emitter http://wiki.seeedstudio.com/Grove-Infrared_Emitter/ with Grove Shield for micro:bit v2.0.
By specification it using TSAL6200 diode https://www.vishay.com/docs/81010/tsal6200.pdf

**Comment by nicolas691799** [comment]
Hello,

i have the same issue with a standard infrared LED. Works on V1, but not on latest PXT.

NOT WORKING :
version makecode.microbit.org :  2.1.38
version Microsoft MakeCode :  5.30.28
version microbit runtime :  pxtgc-0

WORKING :
makecode.microbit.org version:  1.2.13
Microsoft MakeCode version:  4.4.7
microbit runtime version:  v2.1.1

Since i don't know how to debug, i don't understand what causes the issue : PXT, Mbit runtinme or something else... Also tried to read all changelogs but....

Bye

**Comment by KGalea** [comment]
Thank you for these comments. As a first time user of this project I figured I had done something wrong.. however these comments saved me.. copying the javascript from latest make code into https://makecode.microbit.org/v1 and the code started working.. magical.. thank you so much for this fun project (although my train isn't as happy as me, when the IR first worked it drove off the table and smashed.. just a little rebuilding required) :)

**Comment by philipphenkel** [comment]
Thanks for your feedback and sorry for answering so late. Recent MakeCode seem to have broken the code.
As a first step, I updated the Readme to reflect that only v0 and v1 are supported (https://github.com/philipphenkel/pxt-powerfunctions/commit/d6b195ac64cf48d3969238e443b1fe7ac097e34f)

Of course, a fix would be even better. I'm accepting pull-requests :)

**Comment by AlbanT** [comment]
Ahhh this explains a lot :)
I added a transistor for switching as I expected that the current to the led was an issue.
But after confirming the circuit works using a Wemos D1 I came back and discovered this open issue...
My son would be very grateful if it works again with the new MakeCode. In the meantime I'll show him where he can find V1...
Thanks for this extension!!!!

**Comment by philipphenkel** [comment]
@EmmetBrickHacker @nicolas691799 @KGalea @AlbanT I released version 1.4.0 with a highly improved the IR signal precision, especially on the the latest versions of MakeCode. Today, I tested only with an oscilloscope - no lego bricks involved so far. Therefore I'm looking forward to feedback from you.

**Comment by nicolas691799** [comment]
Hello all
I confirm version 1.4.0 works on latest makecode ! Tested with a lego train.
Thanks again for this great piece of software. 

Bye
