### ISSUE TITLE
Create a port for m5stack's UIFlow

### ISSUE THREAD

**Issue by martinschierle** [philipphenkel/pxt-powerfunctions#5]
This is a fantastic project, thanks for doing this!
I wanted to ask if it might be possible to port this over to M5Stack's UIFLow (also blockly based). m5stack is a series of nice little modules based on ESP32, many of them coming with IR LED built in (e.g. [m5stick](https://m5stack.com/products/stick-c) and [m5atom](https://github.com/m5stack/M5Atom)). These are perfect to use with lego, many of their modules are lego-compatible, see e.g. the [m5stack fire](https://m5stack.com/products/fire-iot-development-kit)

**Comment by philipphenkel** [comment]
Thanks for your feedback!
Currently, I don't have any plans to port this library to C/C++. In case you want to do it, I recommend using an Arduino library as a base.
